create table if not exists public.energy_readings (
  id bigint generated by default as identity primary key,
  device_id text not null,
  recorded_at timestamptz not null default now(),
  watts numeric,
  voltage numeric,
  current numeric,
  energy_kwh numeric
);

create index if not exists energy_readings_device_time_idx
on public.energy_readings(device_id, recorded_at desc);

alter table public.energy_readings enable row level security;

-- For a private single-user deployment, keep inserts/reads server-side
-- or add authenticated policies after enabling Supabase Auth.